CREATE DATABASE LibrarySystem

USE LibrarySystem

DBCC CHECKIDENT ('Admins', RESEED, 0);
DBCC CHECKIDENT ('Staffs', RESEED, 0);
DBCC CHECKIDENT ('Members', RESEED, 0);
DBCC CHECKIDENT ('Books', RESEED, 0);

DELETE FROM Admins
DELETE FROM Staffs
DELETE FROM Members
DELETE FROM Books