//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwMembers
    {
        public int MemberId { get; set; }
        public string MemberFirstName { get; set; }
        public string MemberLastName { get; set; }
        public string MemberEmail { get; set; }
        public string MemberUsername { get; set; }
        public string MemberPassword { get; set; }
        public Nullable<System.DateTime> MemberRegistrationDate { get; set; }
    }
}
